name: 🧪 Testes Unitários

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch para executar os testes"
        required: false
        default: ""

jobs:
  unit-tests:
    name: Executar Testes Unitários
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: 🐦 Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.1"
          channel: "stable"
          cache: true

      - name: 📦 Instalar dependências
        run: flutter pub get

      - name: 🔧 Gerar arquivos de mock
        run: dart run build_runner build --delete-conflicting-outputs

      - name: 🧪 Executar testes unitários
        run: flutter test
